import '../gallery_screen/widgets/gallery_item_widget.dart';import 'bloc/gallery_bloc.dart';import 'models/gallery_item_model.dart';import 'models/gallery_model.dart';import 'package:flutter/material.dart';import 'package:rhs_app/core/app_export.dart';import 'package:rhs_app/widgets/app_bar/appbar_leading_image.dart';import 'package:rhs_app/widgets/app_bar/appbar_title.dart';import 'package:rhs_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:rhs_app/widgets/app_bar/custom_app_bar.dart';class GalleryScreen extends StatelessWidget {const GalleryScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<GalleryBloc>(create: (context) => GalleryBloc(GalleryState(galleryModelObj: GalleryModel()))..add(GalleryInitialEvent()), child: GalleryScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Padding(padding: EdgeInsets.only(left: 24.h, top: 24.v, right: 24.h), child: BlocSelector<GalleryBloc, GalleryState, GalleryModel?>(selector: (state) => state.galleryModelObj, builder: (context, galleryModelObj) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 141.v, crossAxisCount: 2, mainAxisSpacing: 16.h, crossAxisSpacing: 16.h), physics: BouncingScrollPhysics(), itemCount: galleryModelObj?.galleryItemList.length ?? 0, itemBuilder: (context, index) {GalleryItemModel model = galleryModelObj?.galleryItemList[index] ?? GalleryItemModel(); return GalleryItemWidget(model);});})))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 16.v), onTap: () {onTapArrowLeft(context);}), title: AppbarTitle(text: "msg_gallery_hotel_photos".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgClock, margin: EdgeInsets.fromLTRB(24.h, 11.v, 24.h, 16.v))]); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
