import 'bloc/card_added_bloc.dart';import 'models/card_added_model.dart';import 'package:flutter/material.dart';import 'package:rhs_app/core/app_export.dart';import 'package:rhs_app/widgets/app_bar/appbar_leading_image.dart';import 'package:rhs_app/widgets/app_bar/appbar_title.dart';import 'package:rhs_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:rhs_app/widgets/app_bar/custom_app_bar.dart';import 'package:rhs_app/widgets/custom_elevated_button.dart';import 'package:rhs_app/widgets/custom_radio_button.dart';class CardAddedScreen extends StatelessWidget {const CardAddedScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<CardAddedBloc>(create: (context) => CardAddedBloc(CardAddedState(cardAddedModelObj: CardAddedModel()))..add(CardAddedInitialEvent()), child: CardAddedScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 28.v), child: Column(children: [_buildPaymentMethods(context), SizedBox(height: 34.v), _buildPayWithDebitCredit(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildContinue(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 56.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 17.v), onTap: () {onTapArrowLeft(context);}), title: AppbarTitle(text: "lbl_payment".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgQrcode, margin: EdgeInsets.fromLTRB(24.h, 10.v, 24.h, 17.v))]); } 
/// Section Widget
Widget _buildPaymentMethods(BuildContext context) { return Column(children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_payment_methods".tr, style: theme.textTheme.titleMedium), Padding(padding: EdgeInsets.only(bottom: 2.v), child: Text("lbl_add_new_card".tr, style: CustomTextStyles.titleMediumPrimary16))]), SizedBox(height: 23.v), _buildPaymentMethodsGoogle(context, userImage: ImageConstant.imgFrameLightBlue600, googlePay: "lbl_paypal".tr), SizedBox(height: 28.v), _buildPaymentMethodsGoogle(context, userImage: ImageConstant.imgFrame, googlePay: "lbl_google_pay".tr), SizedBox(height: 28.v), _buildPaymentMethodsGoogle(context, userImage: ImageConstant.imgFrameWhiteA70032x32, googlePay: "lbl_apple_pay".tr)]); } 
/// Section Widget
Widget _buildPayWithDebitCredit(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_pay_with_debit_credit".tr, style: theme.textTheme.titleMedium), SizedBox(height: 23.v), Container(width: 380.h, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 26.v), decoration: AppDecoration.outlineBlack9000c.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: BlocSelector<CardAddedBloc, CardAddedState, String?>(selector: (state) => state.radioGroup, builder: (context, radioGroup) {return Padding(padding: EdgeInsets.only(right: 8.h), child: CustomRadioButton(width: 324.h, text: "msg".tr, value: "msg".tr ?? "", groupValue: radioGroup, padding: EdgeInsets.fromLTRB(12.h, 1.v, 30.h, 1.v), isRightCheck: true, onChange: (value) {context.read<CardAddedBloc>().add(ChangeRadioButtonEvent(value: value));}));}))]); } 
/// Section Widget
Widget _buildContinue(BuildContext context) { return CustomElevatedButton(text: "lbl_continue".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 49.v), onPressed: () {onTapContinue(context);}); } 
/// Common widget
Widget _buildPaymentMethodsGoogle(BuildContext context, {required String userImage, required String googlePay, }) { return Container(padding: EdgeInsets.all(24.h), decoration: AppDecoration.outlineBlack9000c.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(children: [CustomImageView(imagePath: userImage, height: 32.adaptSize, width: 32.adaptSize), Padding(padding: EdgeInsets.only(left: 12.h, top: 7.v, bottom: 2.v), child: Text(googlePay, style: theme.textTheme.titleMedium!.copyWith(color: appTheme.whiteA700))), Spacer(), CustomImageView(imagePath: ImageConstant.imgContrast, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 6.v, right: 8.h, bottom: 6.v))])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the confirmPaymentScreen when the action is triggered.
onTapContinue(BuildContext context) { NavigatorService.pushNamed(AppRoutes.confirmPaymentScreen, ); } 
 }
